import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.css";

import CurrencyData from "../components/CurrencyData";
import { useState, useEffect } from "react";

const Home: NextPage = () => {
  const [amount, setAmount] = useState<number>(0);
  const [amountOutPut, setAmountOutPut] = useState<number>(0);

  const [selected, setSelected] = useState<string>("");
  const [selectedOutPut, setSelectedOutPut] = useState<string>(" ");

  useEffect(() => {
    const host = "api.frankfurter.app";

    fetch(
      `https://${host}/latest?amount=${amount}&from=${selected}&to=${selectedOutPut}`
    )
      .then((resp) => resp.json())
      .then((data) => setAmountOutPut(data.rates[selectedOutPut]))
      .catch((error) =>
        console.error(`Error to fetch exchange conversion: ${error.message}`)
      );
  }, [amount, selected, selectedOutPut]); //Add dependencies for useEffect: [amount, selected]

  if(selected === selectedOutPut){
    console.log("SOMOS Iguales")
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Capital Markets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Capital Markets</h1>

        <CurrencyData
          currencyTypeChange="origen"
          disable={false}
          amount={amount}
          setAmount={setAmount}
          selected={selected}
          setSelected={setSelected}
        />

        <CurrencyData
          currencyTypeChange="destino"
          disable
          amount={amountOutPut}
          setAmount={setAmountOutPut}
          selected={selectedOutPut}
          setSelected={setSelectedOutPut}
        />
        {selected === selectedOutPut ? (<p className={styles.errormessage}>Has seleccionado la misma moneda</p>) : null}
      </main>
      <Footer></Footer>
    </div>
  );
};

export default Home;
